apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolios-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolios-service
  template:
    metadata:
      labels:
        app: portfolios-service
    spec:
      containers:
      - name: portfolios-service
        image: portfolios-service
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "KingChunk2025"
        - name: DB_HOST
          value: "host.docker.internal"
        - name: DB_NAME
          value: "financial_app_db"