apiVersion: v1
kind: Service
metadata:
  name: web-frontend-service
spec:
  selector:
    app: web-frontend
  # --- CRITICAL CHANGE ---
  # 'NodePort' exposes this service on a static port on your host machine's IP.
  # This is how you will access the web UI from your browser.
  type: NodePort
  ports:
  - protocol: TCP
    port: 5000       # Port inside the cluster
    targetPort: 5000 # Port on the pod
    #nodePort: 30001 # Optionally, you can specify a port. If omitted, K8s picks one.